# Generated by Django 5.2.4 on 2025-09-10 00:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_category_remove_job_posted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applied_by',
            field=models.ManyToManyField(blank=True, related_name='applied_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
